### ISSUE TITLE
hello, i can't get centerpoint detections from the links in README,because the link is invalid now,please tell me where i can get centerpoint detections

### ISSUE THREAD

**Issue by coding-and-coding** [chisyliu/gnn_pmb_tracker#3]
hello, i can't get centerpoint detections from the links in README,because the link is invalid now,please tell me where i can get centerpoint detections.thank you!

**Comment by chisyliu** [comment]
Hi

I have a copy of centerpoint detections locally, please contact jianan.liu@vitalent.se
